###obtener todos los cityes 
GET http://localhost:3000/api/city

###crear un nuevo city
#  @name createCity
POST http://localhost:3000/api/city
Content-Type: application/json

{
    "name": "simon", 
    "birth_date": "2020-10-10",
    "breed": "1",
    "rescueClass": "1"
}

###ID
 @id = {{createCity.response.body.data.id}}


### obtener un city 
GET http://localhost:3000/api/city/{{id}}


###provinceId
@provinceId = {{createCity.response.body.data.provinceId}}
GET http://localhost:3000/api/city/by-province/{{provinceId}}

###Obtener city 1
GET http://localhost:3000/api/city/by-province/2


### modificar un city (PUT)
PUT http://localhost:3000/api/city/2
Content-Type: application/json

{
    "name": "freya", 
    "birth_date": "25122013",
    "breed": "1"
}



### borrar un city
### DELETE
@idToDelete = {{createCity .response.body.data.id}}
DELETE http://localhost:3000/api/city/{{{{idToDelete}}}}


